### ISSUE TITLE
请求nlu时，报错，能帮忙看一下是什么情况吗

### ISSUE THREAD

**Issue by Shawn314** [TencentCloud/tencentcloud-sdk-cpp#2]
![image](https://user-images.githubusercontent.com/30689370/82867385-5da39d00-9f5d-11ea-922c-e423a44007c3.png)
E0526 14:08:03.868163 199275 nlp_wrapper.cc:37] RequestId=09994ef1-6dd8-4902-9a2f-c5635141575e, ErrorCode=CoreInternalError, ErrorMessage=response `Confidence` IsDouble=false incorrectly

**Comment by zqfan** [comment]
推测应该是返回的字段类型和定义的类型不一致导致的，例如confidence期望返回double型，实际却不是，则会在解析时抛出这个错误。
请到控制台工单系统提单给对应的业务，nlp 自然语言处理，提供requestid给他们排查下，
