### ISSUE TITLE
什么时候出个ios版本的sdk呀，急需

### ISSUE THREAD

**Issue by lnles** [TencentCloud/tencentcloud-sdk-cpp#32]

**Comment by zqfan** [comment]
可以先参考官网api文档中我们的swift签名代码，解决签名后，剩下的就是发起https请求。应下急。
或者使用 API Explorer的代码生成工具，生成swift/C++请求代码，目前还未有objective-c语言的

**Comment by lnles** [comment]
感谢已经使用swift配合Moya实现了 @zqfan
