### ISSUE TITLE
我使用GeneralAccurateOCR，碰到2个问题，麻烦优化

### ISSUE THREAD

**Issue by willeach** [TencentCloud/tencentcloud-sdk-cpp#7]
1、发送请求失败
auto outcome = ocr_client.GeneralAccurateOCR(req);
if (!outcome.IsSuccess())

返回报错：libcurl unable to get local issuer certificate 
我把core里HttpClient.cpp的HttpClient::SendRequest改为
// 	curl_easy_setopt(m_curlHandle, CURLOPT_SSL_VERIFYPEER, 1L);
// 	curl_easy_setopt(m_curlHandle, CURLOPT_SSL_VERIFYHOST, 2L);
	curl_easy_setopt(m_curlHandle, CURLOPT_SSL_VERIFYPEER, 0L);//因没有证书，故改为不检查证书
	curl_easy_setopt(m_curlHandle, CURLOPT_SSL_VERIFYHOST, 0L);//因没有证书，故改为不检查证书

2、提价图片返回json的angel值为0是，返回失败，报：response `Angel` IsDouble=false incorrectly
故将GeneralAccurateOCRResponse.cpp 的line88处改为：
    if (rsp.HasMember("Angel") && !rsp["Angel"].IsNull())
    {
        if (rsp["Angel"].IsDouble())
        {
			m_angel = rsp["Angel"].GetDouble();
        }
        else if (rsp["Angel"].IsInt())
		{
			m_angel = (double)(rsp["Angel"].GetInt());
        }
        m_angelHasBeenSet = true;
    }

**Comment by zqfan** [comment]
1、你需要在环境上安装openssl，最好是较新的版本
2、这个是ocr接口返回的类型和实际不一致的问题吧，你看下实际拿到的什么值

**Comment by zqfan** [comment]
因长时间没有回复,关闭此单.如有新的信息,可以重新打开.
